### ISSUE TITLE
security - eth_accounts reveals all accounts 

### ISSUE THREAD

**Issue by frankiebee** [ethcore/parity-extension#101]
For the users sake it would be nice if eth_accounts only revealed one address/the selectedAddress.

Reasoning for this: I don't want dapps knowing all my accounts and if their is a hide/privatize account button somewhere it is not easy to find.

**Comment by tomusdrw** [comment]
You can select visible accounts in Parity Wallet (`Applications -> Permissions`). We further plan to allow you to select accounts per-dapp basis.
