### ISSUE TITLE
Does not work in "remote wallet" by ssh tunneling

### ISSUE THREAD

**Issue by 3esmit** [ethcore/parity-extension#102]
I followed the instructions here https://github.com/paritytech/parity/wiki/Wallet-Remote-Access
I'm using parity 1.7.2 at ubuntu 16.04 and used the command exactly as in the wiki. 
All works fine expect for parity-extension that can't connect.

**Comment by tomusdrw** [comment]
Any errors in Parity log?
Are you using the latest version of extension and are the options pointing to correct URL?

**Comment by 3esmit** [comment]
Using 2.7.1 browser extension.
I was looking better here now, and it show some errors at extension 
![image](https://user-images.githubusercontent.com/224810/31165524-d535f3e4-a8c1-11e7-9800-bd103a73edd2.png)

and if I check in advanced it shows this 
![image](https://user-images.githubusercontent.com/224810/31165502-b5d96cce-a8c1-11e7-8f82-70dd9871ed92.png)

What is parity log? at console screen no errors, just regular sync stuff.

**Comment by tomusdrw** [comment]
With new version you need to point the node to `127.0.0.1:8546`. It should be done automatically unless you have edited those fields in the paste.

**Comment by 3esmit** [comment]
I just checked that box, show advanced options, to print screen, I never touched any of that fields. Maybe it's not automatically doing this, at least for me.

**Comment by tomusdrw** [comment]
Sorry, I confused the settings. They are correct, although your extension is too old for 1.7.2. Please update to 2.7.3.

**Comment by 3esmit** [comment]
Oh, nice. Would be nice if the extension warned me about this, because for me I'm using latest version https://github.com/paritytech/parity-extension/releases

**Comment by tomusdrw** [comment]
Sorry, too tired today :( There were some code changes in 1.7.2 that caused incompatibility with the extension. The extension has been updated in chrome store and I was expecting it to auto-update for everyone.
I've created a new release right now. Feel free to update manually - out of curiosity, why do you use a manually built version?

**Comment by 3esmit** [comment]
Because I googled 'parity chrome extension' and this was the path forward, I'm not sure why parity didn't offerd me, maybe because I use Chromium Browser, and not Google Chrome.

**Comment by 3esmit** [comment]
BTW, everything works fine in 2.7.3
