### ISSUE TITLE
Performing a transaction doesn't popup the signer dialog

### ISSUE THREAD

**Issue by nteymory** [ethcore/parity-extension#103]
Performing a simple transaction doesn't pop up the signer in the extension's overlay. I'm not sure when this broke. I think it stopped working after I upgraded to parity 1.8.0. If you open parity, you'll see the signer popups there.

There are some errors that get thrown as the plugin is loaded, maybe they are related?

Watching a filter doesn't appear to work anymore either. There is a continuous stream of warnings when attempting to watch a filter.

Example code to reproduce issue: https://gist.github.com/nteymory/446819e6280cf16078cad516a04236a8
Chrome version: 62.0.3202.62
Parity version: 1.8.0-beta
Parity Extension version: 2.7.3

Sample error output from chrome: [console_output.txt](https://github.com/paritytech/parity-extension/files/1404424/console_output.txt)

**Comment by CodeDecent** [comment]
I've been waiting for an update on this.

**Comment by nteymory** [comment]
Upgraded to parity 1.8.2-beta and still exact same problem

**Comment by nteymory** [comment]
In case anyone stumbles across this with a similar problem: I finally got around to testing 2.8.0 and my problem became worse. It turns out this was because I was using my own version of web3.min.js. As soon as removed this and started using whatever the parity plugin injected, my problem went away.

**Comment by nteymory** [comment]
Also, is there any plan to release 2.8.0 to the chrome store any time soon?

**Comment by tomusdrw** [comment]
@nt85 Yes, I need to find time to inspect known issues while working with 1.9 version of Parity.
