### ISSUE TITLE
web3.personal.sign method is missed

### ISSUE THREAD

**Issue by Settler** [ethcore/parity-extension#104]
It seems that `web3.eth.sign` method is deprecated and will be removed from web3js.
At least metamask already warn user about that, if developer call `web3.eth.sign` method. More details are described here:
https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527

Replacement of  `web3.eth.sign` method is `web3.personal.sign`:
https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#sign

Metamask already support it, but parity doesn't seems to.
Parity extension used: 2.7.3
Code to reproduce:
```
const from = web3.eth.accounts[0];
const message = web3.toHex('Hello world!');
web3.personal.sign(message, from, (err, result) => console.log('Err: ' + err + ', result: ' + result));
```
Result:
```web3.personal.sign is not a function```

Is there any roadmap to support `web3.eth.sign` method?

**Comment by tomusdrw** [comment]
`web3.eth.sign` is fine afaik, can you show me links where it mentions deprecation?

Parity doesn't expose `personal` methods for dapps at all since they are not safe (they deal with users' passwords) you can enable them by running `--ws-apis safe,+personal`.

You should also use your own web3 instance and just re-use the provider that we are injecting:
```js
var myWeb3 = new Web3(window.web3.currentProvider)
```
Your instance can expose and run any methods you like, although note that they also need to be supported by the underlying node.

**Comment by Settler** [comment]
From this [post](https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527):

> Developer note: This article discusses a new method available to websites viewed with MetaMask and Mist browsers, called personal_sign. This is replacing eth_sign, and that old method now has a big red warning for your users because it was deprecated for security reasons. It’s left in place only to keep sites running that rely on it.

Security reasons discussed here:
https://github.com/ethereum/go-ethereum/pull/2940

It's strange. I can call `personal.sign` method without password parameter, just with `message`, `address` and `callback`, and Metamask work with it. It shows user popup with request to sign message.
Metamask warn user if I call `eth.sign` method and does not, if I call `personal.sign`. And with warning version, sign isn't working (there is issue on metamask repo for this case).
I cannot understand, who is shifted from API - Metamask, Parity or it is just misunderstanding in web3js docs, and password parameter is optional.

But for now developer cannot work with Metamask and Parity in same way, because `eth.sign` doesn't work in Metamask and Parity doesn't expose `personal.sign`.

Here is an another [issue](https://github.com/0xProject/0x.js/issues/162) of 0x project, where developers suggests to migrate to `web3.personal.sign` without password.

**Comment by tomusdrw** [comment]
At the end of the discussion you can see that `eth_sign` has actaully changed it's behaviour and now works exactly the same as `personal_sign` (although does not require password).

I think the consensus now is to introduce and use https://github.com/ethereum/EIPs/pull/712 which introduces a way for users to sign structured data (that the signers can present in a meaningful way).

That said `eth_sign` is probably going to stay since it's now secure-ish, but not very convenient for users.

**Comment by Settler** [comment]
I see.
Well, `eth_signTypedData` looks very promising. I'll follow this EIP.
For now, we can only ask Metamask to remove user warning message or implement different behaviors for Metamask and Parity extensions. It is sad that previous decisions was not in consensus between all participants.
I think this issue can be closed.

Thank you for info.

**Comment by danfinlay** [comment]
I just found this issue, I'm the MetaMask dev probably most involved in our signing protocols, so feel free to ping me when iterating on this. Firstly, I'd like to apologize that our `personal.sign` method failed to comply with your own version of that method, we did our best to reverse engineer it, but clearly fell a little short.

Glad to hear `signTypedData` might give us a fresh start on signing protocols. :)

**Comment by tomusdrw** [comment]
Parity doesn't support `personal.sign` method at all and `eth_sign` was also "reverse engineered" while being implemented in Parity. I would be more than happy to completely remove all of those methods from the RPC (we don't have `personal_` enabled by default on purpose).

@danfinlay I think there is a lot of confusion between RPC-supported methods and Signer/Wallet-supported methods, please ping me on Gitter or by email, maybe we could work together on specifying some sort of separation here. I was thinking on introducing a `wallet_` namespace that could cover all account-touching methods (`eth_sign`, `eth_sendTransaction`, `eth_signTransaction`, `eth_signTypedData`, `personal_newAccount`, etc.). That would make it clear which layer is responsible to handle those and would also make overloaded `eth_` namespace a bit leaner.

**Comment by danfinlay** [comment]
I entirely agree that a signer separation is needed, `wallet_` would seem like a fine namespace for it. Will ping you on Gitter.
