### ISSUE TITLE
Bandwidth usage of Parity extension when connected to remote server

### ISSUE THREAD

**Issue by gaia** [ethcore/parity-extension#110]
I don't have Parity installed on my (Win10) machine. I have the Chrome extension and parity is running on a VPS (Ubuntu Xenial).

The Parity Chrome Extension uses copious amounts of bandwidth when I have the SSH tunnel to the node active.

It is my impression this is the default behavior. But is there a setting in parity (node or client) which I can use to diminish the amount of bandwidth my local computer uses when connected to  the node? It does so even when I don't have a Parity tab (localhost:8180) open.

**Comment by tomusdrw** [comment]
Answered in Parity issue. No settings currently are present, the ongoing efforts to improve Parity Wallet in version 1.9 also include minimizing the amount of data sent between the browser and the node and this will include Parity Extension as well.
