### ISSUE TITLE
parity_getDappsAddresses Method not found

### ISSUE THREAD

**Issue by antonioshadji** [ethcore/parity-extension#121]
I'm seeing these errors in the background page for the extension.  Errors like these are streaming in constantly.  

I'm running parity 1.10.2 node on same machine.  
chrome version: Version 66.0.3359.139 (Official Build) (64-bit)
OS: ubuntu 16.04
extension version: 2.9

```
Ws._this2._onMessage @ index.js:26477
index.js:26477 parity_getDappsAddresses(["https://gitter.im"]): -32601: Method not found
 index.js:26477 parity_getDappsAddresses(["https://tpc.googlesyndication.com"]): -32601: Method not found
 index.js:26477 parity_getDappsAddresses(["https://gitter.im"]): -32601: Method not found
index.js:26477 parity_getDappsAddresses(["https://tpc.googlesyndication.com"]): -32601: Method not found
```

**Comment by tomusdrw** [comment]
It's expected, required for backward compatibility with old versions of Parity. We can probably remove it soon(ish) though.
