### ISSUE TITLE
Extension should indicate it's existence

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-extension#24]
So that the website can detect if the extension is installed or not (will be used by Parity to display a prompt to install extension)

**Comment by derhuerst** [comment]
[Symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for) are a less intrusive way to manipulate webpages instead of polluting the global scope with regular keys or manipulating some global object.

**Comment by tomusdrw** [comment]
We may try Symbols, if the content script context and website share the same Global Symbol Registry, otherwise we may need to just alter the DOM in some way: https://developer.chrome.com/webstore/inline_installation#already-installed
