### ISSUE TITLE
Lookup

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-extension#3]
Implement e-mail lookups using `lookup-service` in background thread. Cache the results.

**Comment by derhuerst** [comment]
This is the logic for looking them up & caching them: https://github.com/ethcore/parity/blob/62f158a37655a222328af72c7fccc0b203140493/js/src/redux/providers/registry/middleware.js . Not finished & merged yet.

**Comment by ngotchac** [comment]
I think for now we can just cache the one we query and not listen for all the changes via logs. (especially if using the Parity server)
