### ISSUE TITLE
Parity account selection doesn't look very good in extension

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-extension#39]
@ngotchac could you have a look at this?

![screenshot from 2017-02-02 10-42-38](https://cloud.githubusercontent.com/assets/581548/22544722/411c79ee-e936-11e6-913e-4af91fbf81f3.png)

We need to increase the size of closed iframe, and also fix some stuff in Parity.

It would be cool to test this stuff while developing Parity and also remove any styles overrides from `parity-extension` - maybe we should have better `http://127.0.0.1:8180/embed.html` page to test it?

**Comment by ngotchac** [comment]
@tomusdrw 

This should be fixed with https://github.com/ethcore/parity/pull/4405

**Comment by tomusdrw** [comment]
Great! I think we still need to make the iframe a little bit bigger on our side.

**Comment by ngotchac** [comment]
@tomusdrw This is fixed right? From the latests merged PR, the iframe has full-width & height when open

**Comment by tomusdrw** [comment]
Yup, ready to close.
