### ISSUE TITLE
Parse DOM for profile links

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-extension#5]
- [x] Site-specific detection of profile links (facebook, github, twitter, reddit)
- [x] Using reverse registry to resolve profile name to badges
- [ ] Augmenting DOM with possible badges (indicate that it might be false positive)

**Comment by ngotchac** [comment]
Point 2 is partly done. The `lookup-service` checks the `A` meta-data of the given name. We could find the right `ReverseConfirmed` log from the hash of the given name to see if it has been reversed and confirmed (and then we not confirm by calling the `reverse` method on the found address, if any, to be sure it hasn't been modified). @derhuerst Would that be ok to include it in the `lookup-service` ?

**Comment by ngotchac** [comment]
Last part is in fact #22
