### ISSUE TITLE
Github-specific detecting

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-extension#6]
Use github API to get e-mail address for a profile and resolve it

**Comment by ngotchac** [comment]
Note that this will be limited to 60 requests per hour : https://developer.github.com/v3/#rate-limiting

**Comment by derhuerst** [comment]
There's also https://www.githubarchive.org, which we could use.

**Comment by ngotchac** [comment]
Interesting ! However might be a bit overkill for now
