### ISSUE TITLE
Exponential backoff when refreshing accounts seems broken

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-extension#62]
I run my PR which renamed `parity_getDappsAddresses` to `parity_getDappAddresses` and extension was generating ~300req/s to fetch dapp accounts.

- [ ] Exponentation backoff should work
- [ ] Different methods should be used dependening on version.

**Comment by derhuerst** [comment]
Use [`p-retry`](https://github.com/sindresorhus/p-retry#readme).
