### ISSUE TITLE
Handle correctly Signer Token change

### ISSUE THREAD

**Issue by ngotchac** [ethcore/parity-extension#63]
The extension cannot recover from a change of the Signer Token (if the extension token is no more working, ie. when changing the Parity directory)

**Comment by tomusdrw** [comment]
It does work after you open a UI. Probably the extension should do it on it's own.

**Comment by ngotchac** [comment]
Ah okay, sorry I just logged after having seen this bug on @rphmeier laptop without actually testing on my side.

**Comment by tomusdrw** [comment]
Closing since I believe it works correctly.
