### ISSUE TITLE
eth_sign method breaks signer

### ISSUE THREAD

**Issue by gbalabasquer** [ethcore/parity-extension#67]
I'm not sure if it is an issue for this project or should go to the main one.
I'm working on a project that requires signing offchain messages. It is working with metamask with a new method they implemented called personal_signer.
I wanted to check how it worked with the parity plugin. Of course personal_sign doesn't work as it is a specific implementation, however eth_sign is breaking the parity plugin and also the UI.

I'm using parity 1.6.3.

<img width="1061" alt="screen shot 2017-03-17 at 8 45 18 pm" src="https://cloud.githubusercontent.com/assets/12644398/24066651/2a193018-0b53-11e7-95cf-3b23e12c9a31.png">

It can be reproduced easily using the eth_sign button on this link:

https://flyswatter.github.io/js-eth-personal-sign-examples/ 

After this happens I do not have other option than killing parity process and start again.

**Comment by tomusdrw** [comment]
I've posted your issue in Parity repo, it's most probably a bug there. Do you know if it works fine on `beta`?

**Comment by gbalabasquer** [comment]
@tomusdrw this is my version: Parity/v1.6.3-beta-ccc5732-20170314/x86_64-macos/rustc1.15.1. So yes it is happening on Beta one.
