### ISSUE TITLE
Allow moving or hiding.

### ISSUE THREAD

**Issue by 5chdn** [ethcore/parity-extension#72]
As the extension might block content.

As discussed here. https://github.com/paritytech/parity/issues/5421

**Comment by rphmeier** [comment]
I think it can be dragged around, and disabling "web3 integration" in the options can be done. Maybe only popping it up when there's something to sign could work too.

**Comment by tomusdrw** [comment]
@rphmeier Note that current master branch was not released yet, so those improvements are not released to the users yet.

**Comment by tomusdrw** [comment]
Closed via #68
