### ISSUE TITLE
Ethereum Sent from Coinbase - transaction confirmed and nothing in wallet? Please help!

### ISSUE THREAD

**Issue by Jacks2High** [ethcore/parity-extension#85]
Hi,

I have just installed the latest version of Parity 1.6.8 and installed on windows 7 with Chrome. I have sent some ether to the one account address from coinbase and nothing has appeared hours after the transaction.

I have checked there are 229 confirmations on etherscan yet nothing is appearing in my wallet. As a new user fairly worried about this, but am hoping its a simple config issue that can be fixed straight away. I have double checked the address and it is correct and checked all the settings and can't see anything wrong.

Please could someone help as soon as possible as i need the ether uregently for an ICO closing soon.

Many thanks

Mickey

**Comment by tomusdrw** [comment]
You're most likely not fully synced. Please follow the steps here:
https://github.com/paritytech/parity/wiki/FAQ#what-can-i-do-when-parity-has-trouble-getting-in-sync

And make sure that your node is on the correct chain and has the best block equal to the one seen on etherscan. (Bottom right corner of the Parity Wallet at `http://127.0.0.1:8180`)

If you still experience issues please join our Gitter channel we'll be able to help you there:
https://gitter.im/paritytech/parity
